name: Temporary document builder

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TARGET_BRANCH: ${{ github.event.pull_request.head.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/upload-artifact@v4
        with:
          name: module6-docx
          path: output/*.docx
          compression-level: 0
          if-no-files-found: error
